// covers: function:workspaceSourceState
//
// The workspace source fingerprint used to hash tool-managed byproduct files
// — `.DS_Store`, coverage databases (`.coverage`, `.coverage.<host>.<pid>`)
// and `__pycache__/*.pyc` — because the hard-exclusion denylist held only
// directory names. Any test or coverage run during a pending review window
// therefore drifted the fingerprint for a change no human made: the review
// verdict became unrecordable (#1224), completion freshness became
// unsatisfiable (#1034), and plan approval re-opened spuriously
// (#1099 / #1218). These tests pin the byproduct names OUT of the
// fingerprint, and pin the explicit `.aidlc-source-paths.json` registration
// escape back IN.

import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { workspaceSourceState } from "../../core/tools/aidlc-lib.ts";
import { cleanupTestProject, createTestProject } from "../harness/fixtures.ts";

const created: string[] = [];
afterEach(() => {
  while (created.length) cleanupTestProject(created.pop());
});

function sourceProject(): string {
  const project = createTestProject();
  created.push(project);
  mkdirSync(join(project, "src"), { recursive: true });
  writeFileSync(join(project, "src", "main.py"), "MAIN = 1\n");
  return project;
}

function fingerprint(project: string): string {
  const state = workspaceSourceState(project);
  expect(state).not.toBeNull();
  return state!.fingerprint;
}

describe("t400 byproduct files do not drift the source fingerprint", () => {
  test(".coverage churn during a review window leaves the fingerprint unchanged", () => {
    const project = sourceProject();
    const before = fingerprint(project);
    // A coverage run rewrites the SQLite database (binary; NUL bytes).
    writeFileSync(join(project, ".coverage"), "SQLite format 3\u0000v1");
    expect(fingerprint(project)).toBe(before);
    writeFileSync(join(project, ".coverage"), "SQLite format 3\u0000v2-rewritten");
    expect(fingerprint(project)).toBe(before);
    rmSync(join(project, ".coverage"));
    expect(fingerprint(project)).toBe(before);
  });

  test("pytest-cov parallel-mode data files are excluded by prefix", () => {
    const project = sourceProject();
    const before = fingerprint(project);
    writeFileSync(join(project, ".coverage.host-1.1234.XYZ"), "SQLite format 3\u0000");
    expect(fingerprint(project)).toBe(before);
  });

  test(".DS_Store appearing anywhere leaves the fingerprint unchanged", () => {
    const project = sourceProject();
    const before = fingerprint(project);
    writeFileSync(join(project, ".DS_Store"), "\u0000Bud1");
    writeFileSync(join(project, "src", ".DS_Store"), "\u0000Bud1");
    expect(fingerprint(project)).toBe(before);
  });

  test("__pycache__ trees regenerated by any Python run are excluded", () => {
    const project = sourceProject();
    const before = fingerprint(project);
    mkdirSync(join(project, "src", "__pycache__"), { recursive: true });
    writeFileSync(
      join(project, "src", "__pycache__", "main.cpython-312.pyc"),
      "\u0000pyc-bytes-v1",
    );
    expect(fingerprint(project)).toBe(before);
    writeFileSync(
      join(project, "src", "__pycache__", "main.cpython-312.pyc"),
      "\u0000pyc-bytes-v2",
    );
    expect(fingerprint(project)).toBe(before);
  });

  test("coverage.xml and htmlcov/ rewritten by a coverage report are excluded", () => {
    const project = sourceProject();
    const before = fingerprint(project);
    writeFileSync(join(project, "coverage.xml"), "<coverage line-rate=\"0.72\"/>\n");
    mkdirSync(join(project, "htmlcov"), { recursive: true });
    writeFileSync(join(project, "htmlcov", "index.html"), "<html>72%</html>\n");
    expect(fingerprint(project)).toBe(before);
    writeFileSync(join(project, "coverage.xml"), "<coverage line-rate=\"0.74\"/>\n");
    writeFileSync(join(project, "htmlcov", "index.html"), "<html>74%</html>\n");
    expect(fingerprint(project)).toBe(before);
  });

  test("a Python virtual environment under any name is excluded by its pyvenv.cfg", () => {
    const project = sourceProject();
    const before = fingerprint(project);
    const site = join(project, ".venv312", "lib", "python3.12", "site-packages", "pkg");
    mkdirSync(site, { recursive: true });
    writeFileSync(join(project, ".venv312", "pyvenv.cfg"), "home = /usr/bin\n");
    writeFileSync(join(site, "__init__.py"), "VERSION = 1\n");
    expect(fingerprint(project)).toBe(before);
    writeFileSync(join(site, "__init__.py"), "VERSION = 2\n");
    expect(fingerprint(project)).toBe(before);
  });

  test("a directory without pyvenv.cfg stays source whatever its name", () => {
    const project = sourceProject();
    const before = fingerprint(project);
    mkdirSync(join(project, "env"), { recursive: true });
    writeFileSync(join(project, "env", "settings.py"), "DEBUG = False\n");
    expect(fingerprint(project)).not.toBe(before);
  });

  test("a real source change still drifts the fingerprint", () => {
    const project = sourceProject();
    const before = fingerprint(project);
    writeFileSync(join(project, "src", "main.py"), "MAIN = 2\n");
    expect(fingerprint(project)).not.toBe(before);
  });

  test("an explicit registry entry opts a byproduct name back in", () => {
    const project = sourceProject();
    writeFileSync(
      join(project, ".aidlc-source-paths.json"),
      JSON.stringify({ version: 1, paths: [".coverage"] }),
    );
    const before = fingerprint(project);
    writeFileSync(join(project, ".coverage"), "SQLite format 3\u0000v1");
    const withFile = fingerprint(project);
    expect(withFile).not.toBe(before);
    writeFileSync(join(project, ".coverage"), "SQLite format 3\u0000v2");
    expect(fingerprint(project)).not.toBe(withFile);
  });
});
